---
test:
  embedded_terraform_defaults: &embedded_terraform_defaults
    embedded_terraform_username: username
    embedded_terraform_password: password
  embedded_terraform:
    <<: *embedded_terraform_defaults
